apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-factory-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-factory-ui
spec:
  template:
    spec:
      containers:
      - name: ui
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
